### ISSUE TITLE
Register Account as admin on the dispatcher

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-dispatcher#1]
This should use work performed on pixelated-project/pixelated-user-agent#10

**Comment by cz8s** [comment]
leap has a file with a list of accounts which should be admins.
There is no way to add the admin-flag to accounts via the webinterface.
You need to add the accounts to the file and run 'leap deploy' on the console

**Comment by lqust** [comment]
Doesn't seem to be valid anymore. If it is, add details and reopen.
