### ISSUE TITLE
Cannot recreate deleted account

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated-project/pixelated-dispatcher#104]
## What
During tests an email was permantly deleted, because of the current problems to send emails, I decided to delete the account and recreate it so I would have the "welcome mail" to use during tests development.
But when I tried to create it, it says the account name is already taken, and when I try to login with says the name/password is not valid. Waiting did not change the result.

## Expected
Should not be possible to recreate the account or reactivate it?

**Comment by varac** [comment]
@tiagoferraz: see the howto "Re-enabling blocked account" at  https://leap.se/en/docs/platform/details/couchdb how to do it

**Comment by tiagoferraz** [comment]
Thanks! I will do it later today!
Closing the issue since it is not a defect.
