### ISSUE TITLE
redirects should not be absolute

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-dispatcher#19]
the dispatcher makes some redirects. For login
for example its to /auth/login
But if the dispatcher runs behind a reverse proxy, it might be reacheable via https://somehost/dispatcher
the redirect should then go to /dispatcher/auth/login/

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
