### ISSUE TITLE
allow users to create account

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-dispatcher#47]
users that create an account on the leap webapp can't automatically sign in because the gpg key is not yet generated. But the dispatcher can't generate the keys because it takes too long.

We need a way to generate a key as soon as as a new account is generated

**Comment by lqust** [comment]
As of now the gpg keys will get created but it will be very slow since the docker image entropy is low and the user will be locked in the loading screen till the keys get generated. Closing this story and opening a new one to make sure the creation is faster
