### ISSUE TITLE
Let user agents store their data in the mounted folder and no longer in docker image

### ISSUE THREAD

**Issue by fbernitt** [pixelated-project/pixelated-dispatcher#61]
Currently the user-agent stores all data in the .leap. To make it easier to change the docker image and avoid a complete resync of the soledad database, all related data should be stored in the mounted folder.

Requirements:
When I log into a new account
And on the command line stop the docker container for user
And on the command line delete the user's data folder
And on the command line delete the docker container for user
And log into the account
Then all mail should be available almost immediatly after the agent started

**Comment by shyba** [comment]
Steps used:
-Vagrant up + vagrant ssh ... (common flow to start everything up)
--login on an account with 91 mails
--waited for sync done signal
--logout
--docker stop container
--docker rm container
--login again... everything ready, all mails there, no need to wait.

There is just one step that I couldnt reproduce:
"And on the command line delete the user's data folder"

I didn't find any files to delete and assumed that removing the container would remove all local files.
Is this right? If yes, issue is ready to be launched! :+1:

**Comment by fbernitt** [comment]
you can find the files in /var/lib/dispatcher/<username>/data/. 
After you ran the user agent once you should see some files in there. 
After the reset_data call, that folder should no longer exist
When you log into the agent again, the folder should be recreated.

**Comment by shyba** [comment]
Ok.
From the last test: If I remove the container without reset_data, there is no need to sync all again.

IMHO, **this card is ok**.

I will just paste this full description from my tests of reset_data for reference.

First try:
* full sync for 91 mails
* logout
* container stopped
* CLI: remove_data <user>

data folder still has a cfg file:
vagrant@vagrant-debian:~$ ls -R /var/lib/dispatcher/<username>/
/var/lib/dispatcher/<username>/:
user.cfg
* container removed
* login and full sync

------All as expected.
Notes:
* Container is quitting with -1 after logout. No need to stop.

Second try:
* all synced, stop client from the CLI without logout.
* refresh page, redirect to auth page again.
* reset_data, then rm -rf on /var/lib/dispatcher/<username>/
* remove container from docker
* try to login again. **Got: Invalid Credentials.** New unrelated issue to be opened.

From this card, all worked as expected.
