### ISSUE TITLE
Logout button should bring user back to login screen

### ISSUE THREAD

**Issue by lieblingswelt** [pixelated-project/pixelated-dispatcher#63]
Currently after logging out, we show a very simple page saying you logged out successfully.

Logging out should bring the user back to the login screen.

**Comment by lqust** [comment]
When the user logs out, we want to allow them to continue using the application in the future, as well as not send them to a dead end. The most useful action for us at this point is allowing the user to log back in. Therefore, we should send the user back to the login screen after logout as the image bleow:

![logout dialog](https://cloud.githubusercontent.com/assets/3587497/5823065/d4dea744-a0c0-11e4-884e-23876302c87d.jpg)

**Comment by fabiopio** [comment]
Some points:

- @lqust this message should to disappear? If yes, how long to do that?

- The font is a bit different of the model image:
![screen shot 2015-01-22 at 11 07 05 am](https://cloud.githubusercontent.com/assets/1228692/5856022/2594a786-a226-11e4-8b85-ace75ac6218a.png)

- "Log out" being displayed as one word "Logout"

**Comment by lieblingswelt** [comment]
@lqust:
- we consciously changed the spelling of logout. 
- For the presentation on the UI, it might be good if someone with the style guide can take a look and adopt?

**Comment by lqust** [comment]
I don't think it needs to disappear. If we decide it should, then we can create another story. The correct style is ".message-panel"

**Comment by fabiopio** [comment]
so @lieblingswelt these three points, just the fonte style is more important for now.
