### ISSUE TITLE
delete dispatcherstaging.wazokazi.is

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-dispatcher#69]
we don't use it anymore because we have
staging.pixelated-project.org now, correct?

**Comment by dudadornelles** [comment]
Yes

**Comment by lqust** [comment]
Have this been deleted already?

**Comment by cz8s** [comment]
deleted image
deleted deploy script from ci-config
deleted deploy stage from go
deleted port forwarding on the hypervisor
