### ISSUE TITLE
provide sane defaults when creating gpg keys

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-dispatcher#70]
the gpg keys are created by the user-agent, but when the user-agent runs inside the dispatcher we should provide a gpg config with sane defaults
see https://github.com/ioerror/duraconf/blob/master/configs/gnupg/gpg.conf

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
