### ISSUE TITLE
Use wheezy for Vagrantfile

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-dispatcher#73]
in the Vagrantfile there's this comment:
```
use testing as we need docker support
```

but we could install docker like this on wheezy:
https://scottlinux.com/2014/05/04/how-to-install-and-run-docker-on-debian-wheezy/

or do i miss sth ?

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
