### ISSUE TITLE
as an admin I want to configure the message on the login screen

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-dispatcher#75]
we have the example accounts from try.pixelated on every
running dispatcher. (even on staging)
It would be nice if the admin could edit a file and that got included in the login screen

**Comment by cz8s** [comment]
we have the problem that the accounts (eve,bob,alice) are hardcoded and we have no visual
distinction between staging and try

**Comment by cz8s** [comment]
staging has the commit history now.
Maybe we should make it look nicer ...

**Comment by cz8s** [comment]
the debian package now installs /etc/pixelated/dispatcher_banner.html and uses that
But maybe we should htmlescape that?
I added a pre tag on staging now. But it will get overwritten on next deploy

**Comment by tiagoferraz** [comment]
Hi @cz8s! How I could test it locally, without messing with dev, staging or try ?

**Comment by lqust** [comment]
Try:
![try](https://cloud.githubusercontent.com/assets/3587497/6329442/1e4b5406-bb4f-11e4-9298-dfa93e5835fe.png)

Staging:
![staging](https://cloud.githubusercontent.com/assets/3587497/6329448/283b52d6-bb4f-11e4-9d1a-929af8758263.png)

I can only believe it was done automagically :o)
