### ISSUE TITLE
when I logout the login screen looks weird

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-dispatcher#76]
see attached image

**Comment by cz8s** [comment]
![screenshot - 02052015 - 02 00 31 pm](https://cloud.githubusercontent.com/assets/369402/6060858/1e3e2936-ad42-11e4-9e56-9989995e43f0.png)

**Comment by albogabriel** [comment]
Looks like the toast message is trapped inside that div's padding. I'll have a look at it when I'm free :)

**Comment by lieblingswelt** [comment]
This only seems to happen on staging. When running the dispatcher locally connecting to try, I cannot reproduce the behaviour. We need to verify it on staging, that means blocking it and verify it once staging is back up.

**Comment by cz8s** [comment]
works in chrome, but not in Firefox
