### ISSUE TITLE
Fix problems found by sslyze (or tell me why we can't)

### ISSUE THREAD

**Issue by fbernitt** [pixelated-project/pixelated-dispatcher#77]
Background:

I just stumbled over a new tool to check the SSL/TLS configuration of a service:

sslyze: https://github.com/iSECPartners/sslyze

After I ran this against the dispatcher, it found some vulnerabilites (see below). Would be great, if we could get rid of them, though I am not sure whether it's possible. Thats because some of them might be related to older versions of python and libraries in wheezy.

Requirements:
- If I run the sslyze check it finds no vulnerability (python sslyze.py --regular host:port)
- (optional) There is an automated test in our build pipeline that runs the check against a running dispatcher

-

Output created with call:

python sslyze.py --regular staging.pixelated-project.org:8080
------------------------------------------------------

 REGISTERING AVAILABLE PLUGINS
 -----------------------------

  PluginOpenSSLCipherSuites
  PluginSessionResumption
  PluginChromeSha1Deprecation
  PluginHeartbleed
  PluginSessionRenegotiation
  PluginCompression
  PluginHSTS
  PluginCertInfo

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   staging.pixelated-project.org:8080  => 213.73.97.228:8080

 SCAN RESULTS FOR STAGING.PIXELATED-PROJECT.ORG:8080 - 213.73.97.228:8080
 ------------------------------------------------------------------------

  * Deflate Compression:
      VULNERABLE - Server supports Deflate compression

  * Session Renegotiation:
      Client-initiated Renegotiations:   VULNERABLE - Server honors client-initiated renegotiations
      Secure Renegotiation:              OK - Supported

  * Certificate - Content:
      SHA1 Fingerprint:                  5f5845c1183e256d17fcf8d23146131008cd6d1f
      Common Name:                       pixelated.try.pixelated-project.org
      Issuer:                            pixelated.try.pixelated-project.org
      Serial Number:                     97530ABC0444CF6E
      Not Before:                        Feb  6 07:43:03 2015 GMT
      Not After:                         Feb  3 07:43:03 2025 GMT
      Signature Algorithm:               sha1WithRSAEncryption
      Key Size:                          2048 bit
      Exponent:                          65537 (0x10001)

  * Certificate - Trust:
      Hostname Validation:               FAILED - Certificate does NOT match staging.pixelated-project.org
      "Mozilla NSS - 08/2014" CA Store:  FAILED - Certificate is NOT Trusted: self signed certificate
      "Microsoft - 08/2014" CA Store:    FAILED - Certificate is NOT Trusted: self signed certificate
      "Apple - OS X 10.9.4" CA Store:    FAILED - Certificate is NOT Trusted: self signed certificate
      "Java 6 - Update 65" CA Store:     FAILED - Certificate is NOT Trusted: self signed certificate
      Certificate Chain Received:        ['pixelated.try.pixelated-project.org']

  * Certificate - OCSP Stapling:
      NOT SUPPORTED - Server did not send back an OCSP response.

  * TLSV1_2 Cipher Suites:
      Server rejected all cipher suites.

  * Session Resumption:
      With Session IDs:                  NOT SUPPORTED (0 successful, 5 failed, 0 errors, 5 total attempts).
      With TLS Session Tickets:          NOT SUPPORTED - TLS ticket assigned but not accepted.

  * SSLV2 Cipher Suites:
      Server rejected all cipher suites.

  * TLSV1_1 Cipher Suites:
      Server rejected all cipher suites.

  * TLSV1 Cipher Suites:
      Preferred:                       
                 AES256-SHA                    -              256 bits      HTTP 302 Found - /auth/login?next=%2F
      Accepted:                        
                 CAMELLIA256-SHA               -              256 bits      HTTP 302 Found - /auth/login?next=%2F
                 AES256-SHA                    -              256 bits      HTTP 302 Found - /auth/login?next=%2F
                 CAMELLIA128-SHA               -              128 bits      HTTP 302 Found - /auth/login?next=%2F
                 AES128-SHA                    -              128 bits      HTTP 302 Found - /auth/login?next=%2F
                 DES-CBC3-SHA                  -              112 bits      HTTP 302 Found - /auth/login?next=%2F

  * SSLV3 Cipher Suites:
      Server rejected all cipher suites.

Unhandled exception when processing --heartbleed: 
socket.timeout - timed out

 SCAN COMPLETED IN 5.50 S
 ------------------------

**Comment by shyba** [comment]
I got this list of things that needs to be checked on SSL CA with Ola and probably we need to test if those items are being checked on SSL connections:
* Expiry date
* Revocation (OCSP?)
* Cert usage
* Cert chain

Probably most of them are checked by underling libraries, but it is good to make sure that they are doing this properly by testing them. In this way we get rid of vulnerabilities due to lack of checking on ssl libs.

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
