### ISSUE TITLE
Elements on login screen should be well aligned

### ISSUE THREAD

**Issue by lieblingswelt** [pixelated-project/pixelated-dispatcher#78]
As a user, I want the login screen to look nice and harmonically. That means we need to tidy up the elements we have on the login screen that are currently misaligned (see image).
- align logout message
- center Pixelated Image
- align form elements 

This is a spinoff from #76.

![screen shot 2015-02-16 at 14 37 00](https://cloud.githubusercontent.com/assets/5365960/6212882/35ef11fc-b5ea-11e4-9dd0-7f91fdbd36f6.png)

**Comment by albogabriel** [comment]
I couldn't get my dispatcher to work again, so I could not log in and log out in order to see all possible warning and error messages on the login page and fix their styling.

Will try to make it work again Today and, when it does work, I'll get back to this story.

**Comment by cz8s** [comment]
I don't know if I am picky now, but the login button is very close to the border of the white box when
there is the yellow banner on top.

**Comment by cz8s** [comment]
![pixelated - login - pentadactyl_006](https://cloud.githubusercontent.com/assets/369402/6829554/6a031136-d314-11e4-8da2-07ed3e994ca9.png)

**Comment by albogabriel** [comment]
That's true; I couldn't see it locally, but I saw it on try now.

I'm checking some code in right now that should fix this.

Please, keep being picky, @cz8s ! :)

**Comment by neissi** [comment]
Albo and I did QA locally in my machine, and login screen looks aligned now.
