### ISSUE TITLE
Remove --provider--fingerprint option from dispatcher

### ISSUE THREAD

**Issue by fbernitt** [pixelated-project/pixelated-dispatcher#79]
Background:

At some point in time we that it to be a good idea to have the possiblity to provide the fingerprint instead of a certificate file. But as we currently don't have that use case at all, we should remove the option.

See #60

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
