### ISSUE TITLE
Make build pipeline public for dispatcher

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-dispatcher#81]
## Why

Contributors should know if the code is working or not before they start working on it.

## Definition of done

I can see the dispatcher build pipeline without being logged in

**Comment by lieblingswelt** [comment]
We also have the dispatcher pipeline on Snap.
Snap Pipeline triggers a dispatcher-packaging pipeline on GoCi.
The old dispatcher pipeline is removed from GoCi.

**Comment by tiagoferraz** [comment]
This can be closed?

**Comment by rafaelzlisboa** [comment]
not yet, we don't trigger the package on Go

**Comment by lieblingswelt** [comment]
Sorry I wasn't clear that I just updated the Definition of Done
