### ISSUE TITLE
Automatically test if test users in try.pixelated are still working

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-dispatcher#82]
## Why
Sometimes LEAP accounts get in to an inconsistent state. When that happens, account becomes unusable. This can turn potential demo users off, so we should know and fix it from time to  time

## Definition of  done
We receive  a notification when Alice, Eve or Bob are not working in less then 24 hours.

**Comment by tiagoferraz** [comment]
@apretto how is this being implemented?

**Comment by tiagoferraz** [comment]
Friday, I was not able  discover why the tests are failling.  I may comeback to this today.

**Comment by tiagoferraz** [comment]
Today, the emails sent on try to try accounts are not arriving in inbox

**Comment by tiagoferraz** [comment]
It was verified that the Try environment was broke during the whole time, so it is not possible to verify that the scripts are not working. Since this issue is open for a long time , I am closing it because of the reasons discussed before.
