### ISSUE TITLE
Prevent 3rd parties to access centralized application logs

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-dispatcher#87]
## Why
Dispatcher logs are currently written to temp, which means that any 3rd party with access to the Dispatcher Manager machine can see logs entries for all dispatchers

## Definition of done
Logs are written to /var/log or using syslog service

---

## Notes
@fbernitt had an idea on how to do this.

**Comment by jeffersonhsta** [comment]
Removed the logging to "/tmp/pixelated.log" file from Pixelated-user-agent
