### ISSUE TITLE
Be able to test local user agent changes inside a local dispatcher

### ISSUE THREAD

**Issue by rafaelzlisboa** [pixelated-project/pixelated-dispatcher#88]
## Why
Being able to test changes on the user agent that concern the dispatcher locally without waiting for the build to pass would allow us to develop quicker and verify changes before committing. For development, it's useful to be able to create a docker container from the current user-agent source, so that we don't need to release a debian package to test how user-agent changes will interact with the dispatcher.

## Definition of done
* After doing a change in the user agent code I have a way to test that change in the local dispatcher installation without committing code

## Notes
* Allow user agent container to be created from source
* The Dockerfiles in pixelated-dispatcher and pixelated-user-agent only setup the containers using `apt-get install pixelated-user-agent`.

**Comment by rafaelzlisboa** [comment]
the remote branch `dev_docker` has some work in progress on this

**Comment by re-nobre** [comment]
This is looks good but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
