### ISSUE TITLE
admin should get an error if dispatcher-proxy waits for lock

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-dispatcher#90]
## Why

the dispatcher-proxy starts but does nothing and does not listen on port 8080 if there is a .lock file 

## Way to reproduce
* stop dispatcher-proxy
* create /var/run/pixelated/pixelated-dispatcher-proxy.pid.lock
* start distpacher-proxy

outcome: dispatcher-proxy is running, but does not listen on port 8080. The output of
```netstat -tulpen | grep 8080``
is empty.

## Definition of done
When starting dispatcher-proxy but a .lock file is already existing, the init-script should fail with an error.

**Comment by cz8s** [comment]
this might be the same for dispatcher-manager

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
