### ISSUE TITLE
Feedback for users where locale is wrongly set in their system

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-dispatcher#92]
## Why
Currently we fail silently is the locale (usually on a debian install) is wrongly set. This makes it a very hard problem to identify/debug

## Definition of done
Either checking if locale is set correctly and return an error if not or throw an error in the log if we run into that problem

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
