### ISSUE TITLE
dispatcher cli help should state the same

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated-project/pixelated-dispatcher#95]
## What
Trying to start Dispatcher Manager to use the fingerprint option, it prints the wrong parameter name in help message
1. Execute ```/usr/bin/python /vagrant/pixelated/pixelated-dispatcher.py```
   a. It's says to use -- fingerprint
2. When using ```--fingerprint```, it says the parameter is not recognized, a differente help message says to use ```provider-fingerprint``.

## Expected
Both message must state the same. 
![screen shot 2015-04-09 at 5 24 42 pm](https://cloud.githubusercontent.com/assets/2946807/7076151/c9f7a596-dedd-11e4-8b12-70653b392a14.png)

**Comment by fbernitt** [comment]
The output is correct as there are two different modes active. In the first case its the client mode, in the second example its the manager mode. These two use different naming for parameters (and actually there is a difference in the fingerprint that is passed to the client and the --provider-fingerprint that is passed to the manager). I would vote to make the different modes more explicit to avoid the ambiguity.

**Comment by tiagoferraz** [comment]
@fbernitt  I see, I also vote to make the differences more explicit, I thought I was executing the same thing. This should also be written somewhere, if someone needs to changes it to another provider that is not Try.

**Comment by rafaelzlisboa** [comment]
moving this to QA too because it relates to #91

**Comment by neissi** [comment]
@jeffersonhsta @fbernitt 

It looks like ok when we run:
``` /usr/bin/python /vagrant/pixelated/pixelated-dispatcher.py manager -b docker --leap-provider try.pixelated-project.org --bind 0.0.0.0 -r /var/lib/dispatcher --sslcert /vagrant/pixelated/test/util/server.crt --sslkey /vagrant/pixelated/test/util/server.key --leap-provider-fingerprint 0E:31:E3:86:94:5A:CE:97:70:20:7A:EE:BD:1F:F1:1B:E4:35:9C:44``` 
The output is clear ```--leap-provider-fingerprint LEAP_PROVIDER_FINGERPRINT```

But when we run: 
```python pixelated/pixelated-dispatcher.py``` 
the output is not clear from where is  ```--fingerprint FINGERPRINT ``` expected.
