### ISSUE TITLE
Tests should not use the defaults ports

### ISSUE THREAD

**Issue by fbernitt** [pixelated-project/pixelated-dispatcher#97]
Currently, when either proxy or manager are running the tests fail because some ports are already occupied. Therefore the test should use different ports in some higher, unused regions.

Requirements:
Given I have a dev environment
When proxy and manager are already running in thet env
And I run the tests
They finish sucessfully

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
