### ISSUE TITLE
[Nagios] Ignore Proxy SSL Warnings about wrong version number

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-dispatcher#98]
we get this in nagios (yet still while parsing /var/log/syslog), but this moved to /car/log/pixelated/dispatcher.log

```
C Apr 23 12:12:42 pixelated tornado.general: WARNING SSL Error on 9 ('0.0.0.0', 58457): [Errno 1] _ssl.c:504: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
```

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
