### ISSUE TITLE
As a concerned sysadmin, I want secure connections between proxy and UA@docker

### ISSUE THREAD

**Issue by shyba** [pixelated-project/pixelated-dispatcher#99]
When we start a user-agent, we need to ask for SSL with -sc and -sk parameters set. This is the last step of this issue: https://github.com/pixelated-project/pixelated-user-agent/issues/149

**Comment by shyba** [comment]
Blocked by: https://github.com/pixelated-project/pixelated-user-agent/issues/383

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
